name: Build and Test

permissions:
  contents: read

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
      - name: Java installieren
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Run Gradle
        run: ./gradlew check
